name: nataliafomin.com
favicon: null
layout_spectrum: 0.18757623829878867
typography_spectrum: 0.3670567434746772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.16007388732396066
  lightness: 0.9645678687375039
  saturation: 0.3368089450523257
  rhythmicContrast: 0.7478473861701787
purpose: []
